### Root Directory of the Project
ROOT_DIR     := ..

### The current path from Root Directory.
DIR          := System

### The List of Sub-Directory which have Makefile
### note: If current directory does not have the sub-directory, Variable "SUBDIR" is empty.
SUBDIRS      :=

### List of source files
### note: If current directory does not have C/ASM source files in "src" directory, CSRC/ASRC is empty.
CSRC := main.c
CSRC += CheckHeaderMain.c
CSRC += protest1.c
CSRC += protest2.c
CSRC += protest3.c
CSRC += protest4.c
CSRC += protest5.c
CSRC += protest6.c
CSRC += protest7.c
CSRC += protest8.c
CSRC += kiotest.c
CSRC += kdisptest.c
CSRC += excnrtest.c
CSRC += perichiptoptest.c

SUB_CINCPATH := -I$(ROOT_DIR)\$(DIR)\include

ASRC := init.s





WS_DIR_NAME  ?= Project
include $(ROOT_DIR)\$(WS_DIR_NAME)\common.mk





### Special compile/assemble
