### Root Directory of the Project
ROOT_DIR     := ../..

### The current path from Root Directory.
DIR          := Project/Arm

### The List of Sub-Directory which have Makefile
### note: If current directory does not have the sub-directory, Variable "SUBDIR" is empty.
SUBDIRS      :=

### List of source files
### note: If current directory does not have C/ASM source files in "src" directory, CSRC/ASRC is empty.
CSRC :=
#CSRC += exiu.c
CSRC += kexiu.c
#CSRC += gic.c
CSRC += kgic.c
#CSRC += mcc.c
CSRC += kmcc.c
#CSRC += nic.c
CSRC += knic.c
#CSRC += timestamp.c
CSRC += ktimestamp.c
#CSRC += xdmac.c
CSRC += kxdmac.c
#CSRC += wdog.c
CSRC += kwdog.c
#CSRC += ipcu.c
CSRC += kipcu.c

ASRC :=




WS_DIR_NAME  ?= Project
include $(ROOT_DIR)/$(WS_DIR_NAME)/common.mk





### Special compile/assemble
