/*
*@Copyright (C) 2010-2020 上海网用软件有限公司
*@date                :2020-09-03
*@author              :董如利
*@brief               :sns 索喜rtos
*@rely                :klib
*@function
*sns 索喜rtos，采用ETK-C语言编写
*设计的主要功能:
*1、
*@version
*1.0.0 2020年09月开始开发
*/

#include <stdlib.h>
#include <string.h>
#include "../../DeviceDriver/LSITop/src/ddtop.h"
#include "../../DeviceDriver/LSITop/src/ddtopfour.h"
#include "../../DeviceDriver/LSITop/src/ddtopone.h"
#include "../../DeviceDriver/LSITop/src/ddtopthree.h"
#include "../../DeviceDriver/LSITop/src/ddtoptwo.h"
#include "ctgpioendtest.h"
#include"ctgpio.h"

K_TYPE_DEFINE_WITH_PRIVATE(CtGpioEndTest, ct_gpio_end_test);
#define CT_GPIO_END_TEST_GET_PRIVATE(o)(K_OBJECT_GET_PRIVATE ((o),CtGpioEndTestPrivate,CT_TYPE_GPIO_END_TEST))

struct _CtGpioEndTestPrivate
{
	kint a;
};
/****************
* DECLS
*/
static void 			ct_gpio_end_test_constructor(CtGpioEndTest *self);
static void 			ct_gpio_end_test_destructor(CtGpioEndTest *self);
/****************
* IMPL
*/
static void ct_gpio_end_test_constructor(CtGpioEndTest *self) 
{
	// CtGpioEndTestPrivate *priv = CT_GPIO_END_TEST_GET_PRIVATE(self);
}

static void ct_gpio_end_test_destructor(CtGpioEndTest *self) 
{
	// CtGpioEndTestPrivate *priv = CT_GPIO_END_TEST_GET_PRIVATE(self);
}
/****************
* PUBLIC
*/
void ct_gpio_end_test(CtGpioEndTest *self,CtGpio *ctGpio)
{
#if 1
	/* PDR */
	ct_gpio_set_ctrl(ctGpio,"PDR", "P60", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P60");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P60", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P60");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P61", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P61");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P61", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P61");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P62", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P62");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P62", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P62");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P63", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P63");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P63", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P63");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P64", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P64");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P64", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P64");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P65", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P65");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P65", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P65");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P66", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P66");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P66", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P66");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P67", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P67");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P67", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P67");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P70", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P70");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P70", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P70");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P71", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P71");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P71", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P71");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P72", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P72");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P72", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P72");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P73", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P73");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P73", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P73");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P74", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P74");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P74", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P74");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P75", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P75");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P75", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P75");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P76", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P76");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P76", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P76");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P77", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P77");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P77", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P77");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P80", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P80");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P80", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P80");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P81", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P81");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P81", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P81");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P82", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P82");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P82", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P82");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P83", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P83");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P83", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P83");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P84", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P84");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P84", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P84");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P85", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P85");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P85", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P85");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P86", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P86");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P86", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P86");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P87", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P87");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P87", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P87");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P90", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P90");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P90", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P90");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P91", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P91");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P91", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P91");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P92", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P92");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P92", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P92");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P93", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P93");
	ct_gpio_set_ctrl(ctGpio,"PDR", "P93", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "P93");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA6", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA6", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA7", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PA7", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PA7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PB4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PB4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PC5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PC5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD6", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PD6", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PD6");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE0", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE0");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE0", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE0");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE1", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE1");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE1", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE1");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE2", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE2");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE2", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE2");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE3", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE3");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE3", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE3");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE4", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE4");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE4", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE4");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE5", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE5");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PE5", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PE5");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF0", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF0");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF0", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF0");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF1", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF1");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF1", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF1");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF2", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF2");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF2", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF2");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF3", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF3");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF3", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF3");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF4", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF4");
	//	ct_gpio_set_ctrl(ctGpio, "PDR", "PF4", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "PDR", "PF4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG6", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG6", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG7", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PG7", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PG7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PH0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PH0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PH0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PH0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PH1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PH1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PH1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PH1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PH2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PH2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PH2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PH2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PH3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PH3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PH3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PH3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW6", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW6", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW7", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PW7", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PW7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ6", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ6", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ7", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PJ7", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PJ7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK6", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK6", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK7", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PK7", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PK7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PL5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PL5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PM4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PM4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PN4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PN4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY4", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY4", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY4");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY5", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY5", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY5");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY6", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY6", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY6");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY7", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PY7", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PY7");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PP0", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PP0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PP0", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PP0");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PP1", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PP1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PP1", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PP1");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PP2", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PP2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PP2", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PP2");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PP3", 1);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PP3");
	ct_gpio_set_ctrl(ctGpio,"PDR", "PP3", 0);
	ct_gpio_get_ctrl(ctGpio,"PDR", "PP3");
#endif
}

CtGpioEndTest* ct_gpio_end_test_new(void) 
{
    CtGpioEndTest *self = k_object_new_with_private(CT_TYPE_GPIO_END_TEST, sizeof(CtGpioEndTestPrivate));
    return self;
}
