/*
*@Copyright (C) 2010-2020 上海网用软件有限公司
*@date                :2020-09-03
*@author              :董如利
*@brief               :sns 索喜rtos
*@rely                :klib
*@function
*sns 索喜rtos，采用ETK-C语言编写
*设计的主要功能:
*1、
*@version
*1.0.0 2020年09月开始开发
*/

#include <stdlib.h>
#include <string.h>
#include "../../DeviceDriver/LSITop/src/ddtop.h"
#include "../../DeviceDriver/LSITop/src/ddtopfour.h"
#include "../../DeviceDriver/LSITop/src/ddtopone.h"
#include "../../DeviceDriver/LSITop/src/ddtopthree.h"
#include "../../DeviceDriver/LSITop/src/ddtoptwo.h"
#include "ctgpiotest.h"
#include"ctgpio.h"

K_TYPE_DEFINE_WITH_PRIVATE(CtGpioTest, ct_gpio_test);
#define CT_GPIO_TEST_GET_PRIVATE(o)(K_OBJECT_GET_PRIVATE ((o),CtGpioTestPrivate,CT_TYPE_GPIO_TEST))

struct _CtGpioTestPrivate
{
	kint a;
};
/****************
* DECLS
*/
static void 			ct_gpio_test_constructor(CtGpioTest *self);
static void 			ct_gpio_test_destructor(CtGpioTest *self);
/****************
* IMPL
*/
static void ct_gpio_test_constructor(CtGpioTest *self) 
{
	// CtGpioTestPrivate *priv = CT_GPIO_TEST_GET_PRIVATE(self);
}

static void ct_gpio_test_destructor(CtGpioTest *self) 
{
	// CtGpioTestPrivate *priv = CT_GPIO_TEST_GET_PRIVATE(self);
}
/****************
* PUBLIC
*/
void ct_gpio_test_test(CtGpioTest *self,CtGpio* ctGpio)
{
	/* EPCR */
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P60", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P60");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P60", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P60");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P61", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P61");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P61", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P61");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P62", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P62");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P62", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P62");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P63", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P63");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P63", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P63");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P80", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P80");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P80", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P80");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P81", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P81");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P81", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P81");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P82", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P82");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P82", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P82");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P83", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P83");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P83", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P83");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P84", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P84");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P84", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P84");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P85", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P85");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P85", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P85");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P86", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P86");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P86", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P86");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P87", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P87");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P87", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P87");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P90", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P90");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P90", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P90");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P92", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P92");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "P92", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "P92");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA7", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PA7", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PA7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PB0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PB0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PB0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PB0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PB1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PB1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PB1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PB1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PB3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PB3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PB3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PB3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PB4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PB4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PB4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PB4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PC5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PC5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD6", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PD6", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PD6");
	//	ct_gpio_set_ctrl(ctGpio, "EPCR", "PE1", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "EPCR", "PE1");
	//	ct_gpio_set_ctrl(ctGpio, "EPCR", "PE1", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "EPCR", "PE1");
	//	ct_gpio_set_ctrl(ctGpio, "EPCR", "PE3", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "EPCR", "PE3");
	//	ct_gpio_set_ctrl(ctGpio, "EPCR", "PE3", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "EPCR", "PE3");
	//	ct_gpio_set_ctrl(ctGpio, "EPCR", "PE5", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "EPCR", "PE5");
	//	ct_gpio_set_ctrl(ctGpio, "EPCR", "PE5", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "EPCR", "PE5");
	//	ct_gpio_set_ctrl(ctGpio, "EPCR", "PF4", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "EPCR", "PF4");
	//	ct_gpio_set_ctrl(ctGpio, "EPCR", "PF4", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "EPCR", "PF4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG6", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG6", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG7", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PG7", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PG7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PH0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PH0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PH0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PH0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PH1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PH1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PH1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PH1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PH2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PH2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PH2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PH2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PH3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PH3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PH3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PH3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW6", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW6", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW7", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PW7", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PW7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ6", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ6", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ7", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PJ7", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PJ7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK6", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK6", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK7", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PK7", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PK7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PL5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PL5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PM1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PM1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PM1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PM1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PM3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PM3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PM3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PM3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PM4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PM4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PM4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PM4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PN1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PN1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PN1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PN1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PN4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PN4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PN4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PN4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY4", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY4", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY4");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY5", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY5", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY5");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY6", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY6", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY6");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY7", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PY7", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PY7");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PP0", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PP0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PP0", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PP0");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PP1", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PP1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PP1", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PP1");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PP2", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PP2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PP2", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PP2");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PP3", 1);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PP3");
	ct_gpio_set_ctrl(ctGpio,"EPCR", "PP3", 0);
	ct_gpio_get_ctrl(ctGpio,"EPCR", "PP3");
  	
	/* DDR */
	ct_gpio_set_ctrl(ctGpio,"DDR", "P60", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P60");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P60", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P60");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P61", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P61");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P61", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P61");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P62", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P62");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P62", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P62");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P63", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P63");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P63", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P63");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P64", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P64");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P64", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P64");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P65", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P65");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P65", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P65");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P66", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P66");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P66", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P66");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P67", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P67");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P67", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P67");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P70", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P70");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P70", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P70");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P71", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P71");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P71", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P71");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P72", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P72");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P72", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P72");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P73", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P73");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P73", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P73");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P74", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P74");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P74", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P74");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P75", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P75");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P75", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P75");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P76", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P76");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P76", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P76");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P77", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P77");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P77", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P77");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P80", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P80");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P80", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P80");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P81", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P81");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P81", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P81");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P82", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P82");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P82", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P82");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P83", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P83");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P83", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P83");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P84", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P84");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P84", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P84");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P85", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P85");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P85", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P85");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P86", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P86");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P86", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P86");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P87", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P87");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P87", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P87");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P90", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P90");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P90", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P90");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P91", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P91");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P91", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P91");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P92", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P92");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P92", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P92");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P93", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P93");
	ct_gpio_set_ctrl(ctGpio,"DDR", "P93", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "P93");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA6", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA6", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA7", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PA7", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PA7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PB4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PB4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PC5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PC5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD6", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PD6", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PD6");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE0", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE0");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE0", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE0");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE1", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE1");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE1", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE1");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE2", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE2");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE2", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE2");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE3", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE3");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE3", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE3");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE4", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE4");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE4", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE4");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE5", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE5");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PE5", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PE5");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF0", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF0");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF0", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF0");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF1", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF1");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF1", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF1");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF2", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF2");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF2", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF2");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF3", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF3");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF3", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF3");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF4", 1 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF4");
	//	ct_gpio_set_ctrl(ctGpio, "DDR", "PF4", 0 );
	//	ct_gpio_get_ctrl(ctGpio, "DDR", "PF4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG6", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG6", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG7", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PG7", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PG7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PH0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PH0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PH0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PH0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PH1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PH1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PH1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PH1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PH2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PH2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PH2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PH2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PH3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PH3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PH3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PH3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW6", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW6", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW7", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PW7", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PW7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ6", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ6", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ7", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PJ7", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PJ7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK6", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK6", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK7", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PK7", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PK7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PL5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PL5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PM4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PM4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PN4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PN4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY4", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY4", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY4");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY5", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY5", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY5");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY6", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY6", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY6");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY7", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PY7", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PY7");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PP0", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PP0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PP0", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PP0");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PP1", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PP1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PP1", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PP1");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PP2", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PP2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PP2", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PP2");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PP3", 1);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PP3");
	ct_gpio_set_ctrl(ctGpio,"DDR", "PP3", 0);
	ct_gpio_get_ctrl(ctGpio,"DDR", "PP3");
}

CtGpioTest* ct_gpio_test_new(void) 
{
    CtGpioTest *self = k_object_new_with_private(CT_TYPE_GPIO_TEST, sizeof(CtGpioTestPrivate));
    return self;
}
