/*
*
*@Copyright (C) 2010-2019 贵阳高新网用软件有限公司
*@date : 2020-09-02
*@author : THH
*@brief : CtImR2y
*@rely : klib.h
*@function : 按ETK规范抄写索喜源代码
*@version : 1.0.0 能正常上屏显示图像
*
*/


#ifndef __CT_IM_R2Y_H__
#define __CT_IM_R2Y_H__


#include <klib.h>
#include "driver_common.h"
#include "ddim_typedef.h"

#define CT_TYPE_IM_R2Y                  (ct_im_r2y_get_type())
#define CT_IM_R2Y(obj)                    (K_TYPE_CHECK_INSTANCE_CAST (obj, CtImR2y)) 
#define CT_IS_IM_R2Y(obj)               (K_TYPE_CHECK_INSTANCE_TYPE (obj, CT_TYPE_IM_R2Y)) 

#define D_IM_R2Y_SRC_IMG_PIXS_WIDTH	(640)
#define D_IM_R2Y_SRC_IMG_PIXS_LINES	(480)

#define D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_U8			(D_IM_R2Y_SRC_IMG_PIXS_WIDTH)
#define D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_P12			(D_IM_R2Y_SRC_IMG_PIXS_WIDTH * 3 / 2)
#define D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_U16			(D_IM_R2Y_SRC_IMG_PIXS_WIDTH * 2)
#define D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_BAY_U16			(D_IM_R2Y_SRC_IMG_PIXS_WIDTH * 2)



#define D_IM_R2Y_DST_IMG_PIXS_WIDTH	(640)
#define D_IM_R2Y_DST_IMG_PIXS_LINES	(480)

#define D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC444_Y			(D_IM_R2Y_DST_IMG_PIXS_WIDTH)
#define D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC444_C			(D_IM_R2Y_DST_IMG_PIXS_WIDTH)

#define D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_Y			(D_IM_R2Y_DST_IMG_PIXS_WIDTH)
#define D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_C			(D_IM_R2Y_DST_IMG_PIXS_WIDTH)

#define D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC420_Y			(D_IM_R2Y_DST_IMG_PIXS_WIDTH)
#define D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC420_C_P		(D_IM_R2Y_DST_IMG_PIXS_WIDTH / 2)
#define D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC420_C_SP		(D_IM_R2Y_DST_IMG_PIXS_WIDTH)



#define D_IM_R2Y_IMG_MEM_IN_ADDR_TOP					(gctImR2yInAddr)

#define D_IM_R2Y_IMG_MEM_IN_RGB_ADDR_TOP				(D_IM_R2Y_IMG_MEM_IN_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_IN_RGB_U8_BYTES				(D_IM_R2Y_SRC_IMG_PIXS_WIDTH * D_IM_R2Y_SRC_IMG_PIXS_LINES * 3)
#define D_IM_R2Y_IMG_MEM_IN_RGB_P12_BYTES				(D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_P12 * D_IM_R2Y_SRC_IMG_PIXS_LINES * 3)
#define D_IM_R2Y_IMG_MEM_IN_RGB_U16_BYTES				(D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_U16 * D_IM_R2Y_SRC_IMG_PIXS_LINES * 3)
#define D_IM_R2Y_IMG_MEM_IN_BAY_U16_BYTES				(D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_BAY_U16 * D_IM_R2Y_SRC_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_IN_RGB_U8_R_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_IN_RGB_U8_G_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_U8_R_ADDR_TOP + D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_U8 * D_IM_R2Y_SRC_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_IN_RGB_U8_B_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_U8_G_ADDR_TOP + D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_U8 * D_IM_R2Y_SRC_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_IN_RGB_P12_R_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_IN_RGB_P12_G_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_P12_R_ADDR_TOP + D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_P12 * D_IM_R2Y_SRC_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_IN_RGB_P12_B_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_P12_G_ADDR_TOP + D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_P12 * D_IM_R2Y_SRC_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_IN_RGB_U16_R_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_IN_RGB_U16_G_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_U16_R_ADDR_TOP + D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_U16 * D_IM_R2Y_SRC_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_IN_RGB_U16_B_ADDR_TOP			(D_IM_R2Y_IMG_MEM_IN_RGB_U16_G_ADDR_TOP + D_IM_R2Y_SRC_IMG_GLOBAL_WIDTH_RGB_U16 * D_IM_R2Y_SRC_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_IN_BAY_ADDR_TOP				(D_IM_R2Y_IMG_MEM_IN_ADDR_TOP)


#define D_IM_R2Y_IMG_MEM_OUT_ADDR_TOP					(gctImR2yOutAddr[0])

#define D_IM_R2Y_IMG_MEM_OUT_YCC_ADDR_TOP				(D_IM_R2Y_IMG_MEM_OUT_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_OUT_YCC444_BYTES				(D_IM_R2Y_DST_IMG_PIXS_WIDTH * D_IM_R2Y_DST_IMG_PIXS_LINES * 3)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_BYTES				(D_IM_R2Y_DST_IMG_PIXS_WIDTH * D_IM_R2Y_DST_IMG_PIXS_LINES * 2)
#define D_IM_R2Y_IMG_MEM_OUT_YCC420_BYTES				(D_IM_R2Y_DST_IMG_PIXS_WIDTH * D_IM_R2Y_DST_IMG_PIXS_LINES * 3 / 2)

#define D_IM_R2Y_IMG_MEM_OUT_YCC444_Y_ADDR_TOP			(D_IM_R2Y_IMG_MEM_OUT_YCC_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_OUT_YCC444_CB_ADDR_TOP			(D_IM_R2Y_IMG_MEM_OUT_YCC444_Y_ADDR_TOP  + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC444_Y * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC444_CR_ADDR_TOP			(D_IM_R2Y_IMG_MEM_OUT_YCC444_CB_ADDR_TOP + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC444_C * D_IM_R2Y_DST_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP			(D_IM_R2Y_IMG_MEM_OUT_YCC_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP			(D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP  + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_Y * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CR_ADDR_TOP			(D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_C * D_IM_R2Y_DST_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP_0		(D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_0		(D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CR_ADDR_TOP_0		(D_IM_R2Y_IMG_MEM_OUT_YCC422_CR_ADDR_TOP)

#define D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP_1		(D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_0 + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_C * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_1		(D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP_1  + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_Y * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CR_ADDR_TOP_1		(D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_1 + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_C * D_IM_R2Y_DST_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP_2		(D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_1 + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_C * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_2		(D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP_2  + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_Y * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CR_ADDR_TOP_2		(D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_2 + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_C * D_IM_R2Y_DST_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP_3		(D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_2 + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_C * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_3		(D_IM_R2Y_IMG_MEM_OUT_YCC422_Y_ADDR_TOP_3  + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_Y * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC422_CR_ADDR_TOP_3		(D_IM_R2Y_IMG_MEM_OUT_YCC422_CB_ADDR_TOP_3 + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC422_C * D_IM_R2Y_DST_IMG_PIXS_LINES)

#define D_IM_R2Y_IMG_MEM_OUT_YCC420_Y_ADDR_TOP			(D_IM_R2Y_IMG_MEM_OUT_YCC_ADDR_TOP)
#define D_IM_R2Y_IMG_MEM_OUT_YCC420_CB_ADDR_TOP			(D_IM_R2Y_IMG_MEM_OUT_YCC420_Y_ADDR_TOP  + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC420_Y    * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC420_CR_P_ADDR_TOP		(D_IM_R2Y_IMG_MEM_OUT_YCC420_CB_ADDR_TOP + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC420_C_P  * D_IM_R2Y_DST_IMG_PIXS_LINES)
#define D_IM_R2Y_IMG_MEM_OUT_YCC420_CR_SP_ADDR_TOP		(D_IM_R2Y_IMG_MEM_OUT_YCC420_CB_ADDR_TOP + D_IM_R2Y_DST_IMG_GLOBAL_WIDTH_YCC420_C_SP * D_IM_R2Y_DST_IMG_PIXS_LINES)


#define D_IM_R2Y_TBL_MEM_OUT_TCTDATA					(40 * 30 * 4)
#define D_IM_R2Y_TBL_MEM_OUT_TCHSYDATA					(4096 * 2)
#define D_IM_R2Y_TBL_MEM_OUT_TCHSRGBDATA				(256 * 2)

#define D_IM_R2Y_IMG_MEM_OUT2_ADDR_TOP					(gctImR2yOutAddr[1])

#define D_IM_R2Y_TBL_MEM_OUT_ADDR_TOP_TCTDATA			(D_IM_R2Y_IMG_MEM_OUT2_ADDR_TOP)
#define D_IM_R2Y_TBL_MEM_OUT_ADDR_TOP_TCHSYDATA			(D_IM_R2Y_IMG_MEM_OUT2_ADDR_TOP)
#define D_IM_R2Y_TBL_MEM_OUT_ADDR_TOP_TCHSRDATA			(D_IM_R2Y_TBL_MEM_OUT_ADDR_TOP_TCHSYDATA + D_IM_R2Y_TBL_MEM_OUT_TCHSYDATA)
#define D_IM_R2Y_TBL_MEM_OUT_ADDR_TOP_TCHSGDATA			(D_IM_R2Y_TBL_MEM_OUT_ADDR_TOP_TCHSRDATA + D_IM_R2Y_TBL_MEM_OUT_TCHSRGBDATA)
#define D_IM_R2Y_TBL_MEM_OUT_ADDR_TOP_TCHSBDATA			(D_IM_R2Y_TBL_MEM_OUT_ADDR_TOP_TCHSGDATA + D_IM_R2Y_TBL_MEM_OUT_TCHSRGBDATA)


typedef struct _CtImR2y CtImR2y;
typedef struct _CtImR2yPrivate CtImR2yPrivate;

struct _CtImR2y 
{
	KObject parent;
};

extern ULONG gctImR2yInAddr;
extern ULONG gctImR2yOutAddr[2];

KConstType ct_im_r2y_get_type(void);
CtImR2y* ct_im_r2y_new(void);
CtImR2y* ct_im_r2y_get(void);


///
VOID ct_im_r2y_get_loop_val(self->ctImR2y, UCHAR pipeNo, UCHAR* loopSta, UCHAR* loopEnd );
VOID ct_im_r2y_set_gamma_on( UCHAR pipeNo );
VOID ct_im_r2y_handler( UINT32* result, UINT32 userParam );

#endif /* __CT_IM_R2Y_H__ */
