### Root Directory of the Project
ROOT_DIR     := ../..

### The current path from Root Directory.
DIR          := Project/PalladiumTest

### The List of Sub-Directory which have Makefile
### note: If current directory does not have the sub-directory, Variable "SUBDIR" is empty.
SUBDIRS      :=

### List of source files
### note: If current directory does not have C/ASM source files in "src" directory, CSRC/ASRC is empty.
CSRC :=
CSRC += ddimusercustomtest.c
CSRC += palladium_test_arm.c
CSRC += palladiumtestb2r.c
CSRC += palladium_test_cache.c
CSRC += palladiumtestcnr.c palladiumtestcnr1.c palladiumtestcnr2.c
CSRC += palladiumtestcommon.c
CSRC += palladium_test_disp.c
CSRC += palladiumtestela.c
#CSRC += palladium_test_exs.c
CSRC += palladiumtestfpt.c
CSRC += palladium_test_gpv.c
CSRC += palladiumtesthdmac.c
CSRC += palladiumtesthdmac0.c
CSRC += palladium_test_hdmac1.c
CSRC += palladiumtesthdmi.c
CSRC += palladiumtestiip.c	palladiumtestiip1.c
CSRC += palladium_test_img.c
CSRC += palladiumtestinterrupta.c  
CSRC += palladiumtestinterruptb.c 
CSRC += palladiumtestinterruptc.c
CSRC += palladium_test_jpeg.c
CSRC += palladium_test_ltm.c
CSRC += palladium_test_mipi.c
CSRC += palladiumtestmxic.c
#CSRC += palladium_test_pwm.c
CSRC += palladiumtestr2y.c palladiumtestr2ycom.c palladiumtestr2ycom2.c
CSRC += palladium_test_raw.c
CSRC += palladium_test_relc.c
#CSRC += palladium_test_sdramc.c
CSRC += palladiumtestshdr.c
CSRC += palladiumtesttmr32.c
CSRC += palladiumtesttmr64.c
CSRC += palladium_test_xch.c
CSRC += palladiumtestpro.c
CSRC += palladiumtestme.c

ASRC :=
ASRC +=

#使用类封装
CSRC += palladiumtestsdramc.c
CSRC += palladiumtestpwm.c
CSRC += palladiumtestexs.c

#新建的拆分类
CSRC += palladiumtestmainexs.c
CSRC += palladiumtestmain2exs.c


WS_DIR_NAME ?= Project
include $(ROOT_DIR)/$(WS_DIR_NAME)/common.mk





### Special compile/assemble
