### Root Directory of the Project
ROOT_DIR     := ../..

### The current path from Root Directory.
DIR          := Project/ComponentTest

### The List of Sub-Directory which have Makefile
### note: If current directory does not have the sub-directory, Variable "SUBDIR" is empty.
SUBDIRS      :=

### List of source files
### note: If current directory does not have C/ASM source files in "src" directory, CSRC/ASRC is empty.
CSRC :=
CSRC += ct_dd_arm.c
CSRC += ct_dd_audio.c
CSRC += ct_dd_cache.c
#CSRC += ct_dd_csio.c
CSRC += ctddcsio.c
CSRC += ctddcsiomain.c
CSRC += ctddcsioprocess.c

CSRC += ct_dd_exiu.c
#CSRC += ct_dd_exs.c
CSRC += ctddexs.c
CSRC += ctddexsmain.c

CSRC += ct_dd_gic.c
#CSRC += ct_dd_gpv.c
CSRC += ctddgpv.c
CSRC += ctddgpvmain.c

#CSRC += ct_dd_hdmac.c
CSRC += ctddhdmac.c
CSRC += ctddhdmacmain.c
#CSRC += ct_dd_hdmac0.c
CSRC += ctddhdmac0.c
CSRC += ctddhdmac0main.c
#CSRC += ct_dd_hdmac1.c
CSRC += ctddhdmac1.c
CSRC += ctddhdmac1main.c
#CSRC += ct_dd_ipcu.c
CSRC += ctddipcu.c
CSRC += ctddipcumain.c

CSRC += ct_dd_i2c.c
#CSRC += ct_dd_pcie_rc.c
CSRC += ctddpcierc.c
CSRC += ctddpciemain.c

#CSRC += ct_dd_pwm.c
CSRC += ctddpwm.c
CSRC += ctddpwmmain.c
##### REMOVE_RELEASE BEGIN #####
# CSRC += ct_dd_relc.c
CSRC += ctddrelc.c
CSRC += ctddrelcmain.c
CSRC += ctddrelcjugde.c
##### REMOVE_RELEASE END #####
CSRC += ct_dd_top.c
CSRC += ctdduart.c ctdduart1.c ctdduart2.c ctdduart3.c
CSRC += ctddxdmasnap.c ctddxdmasnap1.c
CSRC += ctddxdmac.c ctddxdmac1.c
# CSRC += ct_dd_spi.c
CSRC += ctddspimain.c
CSRC += ctddspijudge.c
CSRC += ctddspitest.c
CSRC += ctddspitestone.c
CSRC += ctddspitesttwo.c
CSRC += ctddspitestthree.c
# CSRC += ct_dd_pdm.c
CSRC += ctddpdmmain.c 
CSRC += ctddpdmothertest.c
CSRC += ctddpdmcoretest.c
CSRC += ctddpdmdmatest.c
CSRC += ctddpdmstatustest.c
CSRC += ctddpdmtestone.c
CSRC += ctddpdmtesttwo.c
CSRC += ctddpdmtestthree.c
CSRC += ctddpdmtestfour.c
CSRC += ctddpdmtestfive.c
CSRC += ctddpdmtestsix.c
CSRC += ctimb2r.c ctimb2r1.c ctimb2r2.c ctimb2r3.c ctimb2r4.c ctimb2r5.c ctimb2r6.c ctimb2r7.c \
			ctimb2r8.c ctimb2r9.c ctimb2r10.c

#CSRC += ct_im_bmh.c
CSRC += ctimbmh.c
CSRC += ctimbmh1.c
CSRC += ctimbmh2.c
CSRC += ctimbmh3.c
CSRC += ctimbmh4.c
CSRC += ctimbmh5.c
CSRC += ctimbmh6.c
CSRC += ctimbmh7.c
CSRC += ctimbmh8.c

#CSRC +=ct_im_disp
CSRC += ctimdisp2.c ctimdisp2a.c ctimdisp2b.c ctimdisp2c.c ctimdisp2d.c \
			ctimdisp2e.c ctimdisp2f.c ctimdisp2g.c ctimdisp2h.c ctimdisp2i.c \
			ctimdisp2j.c ctimdisp2k.c ctimdisp2l.c ctimdisp2m.c ctimdisp2n.c \
			ctimdisp2o.c ctimdisp3.c ctimdisp3a.c ctimdisp4.c ctimdisp1.c \
			ctimdisp1a.c ctimdisp1b.c ctimdisp1c.c ctimdisp1d.c ctimdisp1e.c \
			ctimdisp.c imdisp1parent.c imdisp1group.c imdisp2parent.c imdisp2group.c#
#CSRC += ct_im_ela.c
CSRC += ctimela.c
CSRC += ctimela1.c
CSRC += ctimela2.c
CSRC += ctimela3.c
CSRC += ctimela4.c
CSRC += ctimela5.c
CSRC += ctimela6.c
CSRC += ct_im_fpt.c
CSRC += ct_im_iip.c



#杨文
CSRC += ctimfpt.c ctimfpt1.c ctimfpt2.c ctimfpt3.c
CSRC += ctimiipafn.c ctimiipafn1.c
CSRC += ctimiipblend.c
CSRC += ctimiipcfl.c
CSRC += ctimiipcsc.c
CSRC += ctimhdmi.c ctimhdmi1.c

CSRC += ct_im_iip_afn.c
CSRC += ct_im_iip_blend.c
CSRC += ct_im_iip_cfl.c
CSRC += ct_im_iip_csc.c
CSRC += ct_im_iip_flt.c
CSRC += ct_im_iip_frect.c
CSRC += ct_im_iip_frecttbl.c
#CSRC += ct_im_iip_gpc.c
CSRC += ctimiipgpc.c
CSRC += ctimiipgpc1.c
CSRC += ctimiipgpc2.c

#李清
CSRC += ctddmcc.c
CSRC += ctddnic.c
CSRC += ctddpcieep.c
CSRC += ctddpmu.c
CSRC += ctddtimestamp.c
CSRC += ctddtmr32.c
CSRC += ctddtmr64.c
CSRC += ctddudc.c ctddudc1.c
CSRC += ctddwdog.c
CSRC += ctddslimbus.c
CSRC += ctimiipld.c
CSRC += ctimiiplut.c
CSRC += ctimiipmft.c
CSRC += ctimiipmon.c
CSRC += ctimiiputility.c ctimiiputility1.c ctimiiputility2.c
CSRC += ctimimg.c

#王印斌
CSRC += ctimcnr.c ctimcnr1.c ctimcnr2.c ctimcnr3.c ctimcnr4.c ctimcnr5.c \
				ctimcnr6.c ctimcnr7.c ctimcnr8.c ctimcnr9.c ctimcnr10.c ctimcnr11.c \
				ctimcnr12.c ctimcnr13.c ctimcnr14.c
CSRC += ctimiipsl.c
##### REMOVE_ME_RELEASE BEGIN #####
CSRC += ctimme.c
##### REMOVE_ME_RELEASE END #####

##### REMOVE_ME_RELEASE BEGIN #####
ifeq "$(BUILD_IM_ME_OBJ)" "yes"
# target source overwrite only "ctimme.c".
CSRC := ctimme.c
ASRC :=
endif
##### REMOVE_ME_RELEASE END #####

CSRC += ct_im_ltm_rbk.c
CSRC += ctimltmmap.c ctimltmmap1.c ctimltmmap2.c ctimltmmap3.c
CSRC += ctimltmltm.c ctimltmltm1.c ctimltmltm2.c ctimltmltm3.c ctimltmltm4.c ctimltmltm5.c
CSRC += ct_im_mxic.c
CSRC += ct_im_r2y.c
CSRC += ct_im_raw.c
CSRC += ct_im_sdramc.c
CSRC += ct_im_shdr.c
CSRC += ct_im_xch.c
CSRC += ctimjpeg1.c ctimjpeg.c ctimjpeg2.c ctimjpeg3.c ctimjpeg4.c ctimjpeg5.c  ctimjpeg6.c 
CSRC += ct_im_hdmi.c
CSRC += ct_im_mipi.c
CSRC += ctimpro.c
CSRC += ctimpro1.c
CSRC += ctimpro2.c
CSRC += ctimpro3.c
CSRC += ctimpro4.c
CSRC += ctimpro5.c

#陈阳
CSRC += impro11print.c impro12print.c impro13print.c impro14print.c\
		impro10print.c impro15print.c impro16print.c impro17print.c\
		impro21print.c impro22print.c impro23print.c impro24print.c\
		impro20print.c impro25print.c impro26print.c impro27print.c\
		impro271print.c impro274print.c \
		impro30print.c impro31print.c impro32print.c impro33print.c\
		impro311print.c impro314print.c \
		impro5print.c impro7print.c \
		impro81slvs.c improcallback.c improdebug.c\
		impro40print.c impro41print.c impro42print.c impro43print.c\
		impro44print.c impro45print.c impro46print.c impro47print.c impro48print.c\
		impro60print.c impro61print.c impro62print.c impro63print.c impro64print.c\
		ctimpro70.c ctimpro71.c ctimpro72.c ctimpro73.c ctimpro74.c\
		ctimpro75.c ctimpro76.c ctimpro77.c ctimpro78.c ctimpro79.c\
		ctimpro60.c ctimpro61.c ctimpro62.c ctimpro63.c ctimpro64.c\
		ctimpro8.c 	absimproprint.c

#陈元
CSRC += ctimpro.c
CSRC += ctimpro1.c
CSRC += ctimpro11.c
CSRC += ctimpro12.c
CSRC += ctimpro13.c
CSRC += ctimpro14.c
CSRC += ctimpro15.c
CSRC += ctimpro16.c
CSRC += ctimpro17.c
CSRC += ctimpro2.c
CSRC += ctimpro21.c
CSRC += ctimpro22.c
CSRC += ctimpro23.c
CSRC += ctimpro24.c
CSRC += ctimpro25.c
CSRC += ctimpro26.c
CSRC += ctimpro27.c
CSRC += ctimpro3.c
CSRC += ctimpro31.c
CSRC += ctimpro32.c
CSRC += ctimpro33.c
CSRC += ctimpro4.c
CSRC += ctimpro4continue.c
CSRC += ctimpro4last.c
CSRC += ctimpro5.c
CSRC +=ctimraw.c
CSRC +=ctimrawconfig.c
CSRC +=ctimrawvarify.c
CSRC +=ctimrawtest1.c
CSRC +=ctimrawtest2.c

#董如利
CSRC += ctclockclkstopmid.c
CSRC += ctclockclkstopend.c
CSRC += ctclockclkstop.c
CSRC += ctclockfrequency.c
CSRC += ctclockfrequencyend.c
CSRC += ctclockfrequencymid.c
CSRC += ctclockpllcnt.c
CSRC += ctddcoes1help.c
CSRC += ctddcoes3help.c
CSRC += ctddtopfrist.c
CSRC += ctddtopsecond.c
CSRC += ctddtopthird.c
CSRC += ctddtopend.c
CSRC += ctddtop.c
CSRC += ctddtopmain.c
CSRC += ctddtopparent.c
CSRC += ctddtopwrap.c
CSRC += ctgetctrl.c
CSRC += ctgpio.c
CSRC += ctgpiocopy.c
CSRC += ctgpiomidtest.c
CSRC += ctgpioendtest.c
CSRC += ctgpiotest.c
CSRC += ctsetpll.c
CSRC += ctpll.c
CSRC += ctreset.c
CSRC += ctsetctrl.c
CSRC += ctclockclksel.c
CSRC += ctddparameter.c



ASRC :=
ASRC +=





WS_DIR_NAME ?= Project
include $(ROOT_DIR)/$(WS_DIR_NAME)/common.mk





### Special compile/assemble
