### Root Directory of the Project
ROOT_DIR     := ../../..

### The current path from Root Directory.
DIR          := Project/DeviceDriver/Peripheral

### The List of Sub-Directory which have Makefile
### note: If current directory does not have the sub-directory, Variable "SUBDIR" is empty.
SUBDIRS      :=

### List of source files
### note: If current directory does not have C/ASM source files in "src" directory, CSRC/ASRC is empty.
CSRC := dd_audio.c
CSRC +=ddcsio.c
CSRC +=ddcsiocommon.c
CSRC +=ddcsiodma.c
CSRC +=dd_hdmac0.c
CSRC +=dd_hdmac1.c
CSRC +=dd_i2c.c
CSRC += dd_pdm.c
CSRC +=ddpwm.c
CSRC +=ddpwmbranch.c
CSRC +=ddpwmutility.c
CSRC +=ddpwmcolabo.c
CSRC +=ddtmr32.c
CSRC +=ddtmr32interruption.c
CSRC +=ddtmr64.c
CSRC +=ddudc.c
CSRC +=ddudcinterruption.c
CSRC +=ddudcutility.c
CSRC +=dduart.c
CSRC +=dduartbranch.c
CSRC +=dduartcolabo.c
CSRC +=dduartinterrupt.c
CSRC +=ddspi.c
CSRC +=ddspidrive.c
CSRC +=ddspidrivebranch.c
CSRC +=ddspicalculate.c
CSRC +=ddspicolabo.c
CSRC +=ddslimbus.c

ASRC :=
ASRC +=





WS_DIR_NAME ?= Project
include $(ROOT_DIR)/$(WS_DIR_NAME)/common.mk





### Special compile/assemble
