/*
*@Copyright (C) 2010-2020 上海网用软件有限公司
*@date              :2020-09-02
*@author            :郑蛘钊
*@brief             :excnrtest
*@rely              :klib
*@function
*设计的主要功能:
*1、
*2、
*@version
*1.0.0 2020年09月开始开发
*/


#include <stdio.h>
#include <stdlib.h>
#include "milb.h"
#include "chiptop.h"
#if 0
#include "arm.h"
#include "chiptop.h"
#include "exstop.h"
#include "jdsb2r.h"
#include "jdscnr.h"
#include "jdsdisp.h"
#include "jdsela.h"
#include "jdsfpt.h"
#include "jdsiip.h"
#include "jdsimg.h"
#include "jdsjpgdec.h"
#include "jdsjpgenc.h"
#include "jdsltm.h"
#include "jdsmxic.h"
#include "jdspro.h"
#include "jdsr2y.h"
#include "jdsraw.h"
#include "jdsshdr.h"
#include "jdsxch.h"
#include "jmilaum.h"
#include "jmilhdmi.h"
#include "jmlbmh.h"
#include "jsrlot.h"
#include "peripheral.h"
#include "slimbus.h"
#include "sdramc.h"
#include "uart_csio.h"
#include "jdsme.h"
#endif
#include "excnrtest.h"


K_TYPE_DEFINE_WITH_PRIVATE(ExCnrTest, ex_cnr_test);
#define EX_CNR_TEST_GET_PRIVATE(o) (K_OBJECT_GET_PRIVATE((o), ExCnrTestPrivate, EX_TYPE_CNR_TEST))

#define EX_CNR_TEST_RS_PRINTF printf


struct  _ExCnrTestPrivate
{

};
/**
 IMPL
*/
static void ex_cnr_test_constructor(ExCnrTest *self)
{
	ExCnrTestPrivate *priv = EX_CNR_TEST_GET_PRIVATE(self);
}

static void ex_cnr_test_destructor(ExCnrTest *self)
{
	ExCnrTestPrivate *priv = EX_CNR_TEST_GET_PRIVATE(self);
}
/**
 PUBLIC
*/
void ex_cnr_test_exstop_test(ExCnrTest* self)
{
// for PC debug
#if 0
    #define IO_EXSTOP   (*ioExstop2)
    volatile IoExstop* ioExstop2 = (kpointer)0x2B110000;
#endif
    EX_CNR_TEST_RS_PRINTF("EXS TOP\n");
#if 0
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.XDMACLPCTRL           = 0x%lX\n", (kulong)&IO_EXSTOP.XDMACLPCTRL);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.NFLPCTRL              = 0x%lX\n", (kulong)&IO_EXSTOP.NFLPCTRL);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.NFBSSIGCTRL           = 0x%lX\n", (kulong)&IO_EXSTOP.NFBSSIGCTRL);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.SOFTRESET             = 0x%lX\n", (kulong)&IO_EXSTOP.SOFTRESET);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.INTSTAT               = 0x%lX\n", (kulong)&IO_EXSTOP.INTSTAT);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.INTMSK                = 0x%lX\n", (kulong)&IO_EXSTOP.INTMSK);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.SIGMON                = 0x%lX\n", (kulong)&IO_EXSTOP.SIGMON);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.DEBEN                 = 0x%lX\n", (kulong)&IO_EXSTOP.DEBEN);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.CDINSMODCTRL          = 0x%lX\n", (kulong)&IO_EXSTOP.CDINSMODCTRL);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.RELCHPTCTRL           = 0x%lX\n", (kulong)&IO_EXSTOP.RELCHPTCTRL);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.RAMPDCTRL             = 0x%lX\n", (kulong)&IO_EXSTOP.RAMPDCTRL);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.PCIEBIFCTRL           = 0x%lX\n", (kulong)&IO_EXSTOP.PCIEBIFCTRL);
    EX_CNR_TEST_RS_PRINTF("IO_EXSTOP.NETSECPTPCLKSTOPCTRL  = 0x%lX\n", (kulong)&IO_EXSTOP.NETSECPTPCLKSTOPCTRL);

    EX_CNR_TEST_RS_PRINTF(" \n");
#endif
}

void ex_cnr_test_exsgpv_test(ExCnrTest* self)
{
    EX_CNR_TEST_RS_PRINTF("EXS GPV \n");
#if 0
    EX_CNR_TEST_RS_PRINTF("IO_GPV.REMAP           = 0x%p\n", &IO_GPV.REMAP);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.dmy_0004_1FFF);

    EX_CNR_TEST_RS_PRINTF("IO_GPV.AMIB[0]         = 0x%p\n", &IO_GPV.AMIB[0]);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.AMIB[0].dmy_0000_0007);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.AMIB[0].FMBI    = 0x%p\n", &IO_GPV.AMIB[0].FMBI);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.AMIB[0].dmy_000C_001F);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.AMIB[0].SM      = 0x%p\n", &IO_GPV.AMIB[0].SM);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.AMIB[0].FM2     = 0x%p\n", &IO_GPV.AMIB[0].FM2);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.AMIB[0].dmy_0028_003F);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.AMIB[0].WT      = 0x%p\n", &IO_GPV.AMIB[0].WT);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.AMIB[0].AC      = 0x%p\n", &IO_GPV.AMIB[0].AC);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.AMIB[0].dmy_0048_0107);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.AMIB[0].FM      = 0x%p\n", &IO_GPV.AMIB[0].FM);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.AMIB[0].dmy_010C_0FFF);
    for(int i=1; i<14; i++) {
        EX_CNR_TEST_RS_PRINTF("IO_GPV.AMIB[%d]    = 0x%p\n", i, &IO_GPV.AMIB[i]);
    }
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.dmy_10000_41FFF);
    EX_CNR_TEST_RS_PRINTF(" \n");

    EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[0]         = 0x%p\n", &IO_GPV.ASIB[0]);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.ASIB[0].dmy_0000_001F);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[0].SM      = 0x%p\n", &IO_GPV.ASIB[0].SM);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[0].FM2     = 0x%p\n", &IO_GPV.ASIB[0].FM2);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[0].FMA     = 0x%p\n", &IO_GPV.ASIB[0].FMA);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.ASIB[0].dmy_002C_003F);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[0].WT      = 0x%p\n", &IO_GPV.ASIB[0].WT);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.ASIB[0].dmy_0044_00FF);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[0].RQ      = 0x%p\n", &IO_GPV.ASIB[0].RQ);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[0].WQ      = 0x%p\n", &IO_GPV.ASIB[0].WQ);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[0].FM      = 0x%p\n", &IO_GPV.ASIB[0].FM);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.ASIB[0].dmy_010C_0FFF);
    for(int i=1; i<12; i++) {
        EX_CNR_TEST_RS_PRINTF("IO_GPV.ASIB[%d]    = 0x%p\n", i, &IO_GPV.ASIB[i]);
    }
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.dmy_4E000_C1FFF);
    EX_CNR_TEST_RS_PRINTF(" \n");

    EX_CNR_TEST_RS_PRINTF("IO_GPV.IB[0]           = 0x%p\n", &IO_GPV.IB[0]);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.IB[0].dmy_0000_0007);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.IB[0].FMBI      = 0x%p\n", &IO_GPV.IB[0].FMBI);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.IB[0].dmy_000C_001F);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.IB[0].SM        = 0x%p\n", &IO_GPV.IB[0].SM);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.IB[0].FM2       = 0x%p\n", &IO_GPV.IB[0].FM2);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.IB[0].dmy_0028_003F);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.IB[0].WT        = 0x%p\n", &IO_GPV.IB[0].WT);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.IB[0].dmy_0044_0107);
    EX_CNR_TEST_RS_PRINTF("IO_GPV.IB[0].FM        = 0x%p\n", &IO_GPV.IB[0].FM);
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.IB[0].dmy_010C_0FFF);
    for(int i=1; i<4; i++) {
        EX_CNR_TEST_RS_PRINTF("IO_GPV.IB[%d]      = 0x%p\n", i, &IO_GPV.IB[i]);
    }
    EX_CNR_TEST_RS_PRINTF("Reserved               = 0x%p\n", &IO_GPV.dmy_C6000_FFFFF);
    EX_CNR_TEST_RS_PRINTF(" \n");
#endif
}

void ex_cnr_test_cnr_test(ExCnrTest* self)
{
// for PC debug
#if 0
#define IO_CNR_P1       (*ioCnr2P1)
#define IO_CNR_P2       (*ioCnr2P2)
#define IO_CNR_P3       (*ioCnr2P3)
    volatile IoCnrReg* ioCnr2P1 = (kpointer)0x28420000;
    volatile IoCnrReg* ioCnr2P2 = (kpointer)0x28520000;
    volatile IoCnrReg* ioCnr2P3 = (kpointer)0x28620000;
#endif
    EX_CNR_TEST_RS_PRINTF("CNR\n");
#if 0
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.SPRSR          = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.SPRSR);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.ACESEN         = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.ACESEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.SPRTRG         = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.SPRTRG);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.SPRICE         = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.SPRICE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.SPRICF         = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.SPRICF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.HDIV           = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.HDIV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.SPRAXISET      = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.SPRAXISET);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.SPRMOD         = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.SPRMOD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.HSIZE          = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.HSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.VSIZE          = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.VSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.WCTA           = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.WCTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.WCDEF          = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.WCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_REG_RW.CNRWOFSX       = %lX\n", (kulong)&IO_CNR_P1.OTF_REG_RW.CNRWOFSX);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CSPREN       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CGDKEN       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CGDKEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCEN         = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCYTHH       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCYTHV       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCCTHH       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCCTHV       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCYDYM       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCYDYMDT     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCYSCL       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCYSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCYSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCYSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCCSCL       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCCSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCCSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCCSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCSSCL       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCSSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCSSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.MCSSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.MCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCEN         = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCYTHH       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCYTHV       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCCTHH       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCCTHV       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCYDYM       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCYDYMDT     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCYSCL       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCYSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCYSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCYSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCCSCL       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCCSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCCSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCCSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCSSCL       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCSSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCSSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.LCSSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.LCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.BLEND        = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.BLEND);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CESCLOF      = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CESCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CESCLGA      = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CESCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CESCLBD      = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CESCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CPHPT        = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CPHPT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CPHPTK       = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CPHPTK);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CDSCLOF      = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CDSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CDSCLGA      = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CDSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.CDSCLBD      = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.CDSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.WHTMD        = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.WHTMD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRS         = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRS);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRSCBOF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRSCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRSCBGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRSCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRSCBBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRSCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRSCROF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRSCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRSCRGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRSCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRSCRBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRSCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRD         = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRDCBOF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRDCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRDCBGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRDCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRDCBBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRDCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRDCROF     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRDCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRDCRGA     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRDCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OTF_CSPR_REG.SPRDCRBD     = %lX\n", (kulong)&IO_CNR_P1.OTF_CSPR_REG.SPRDCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.SPRSR          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.SPRSR);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.ACESEN         = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.ACESEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.SPRTRG         = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.SPRTRG);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.SPRICE         = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.SPRICE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.SPRICF         = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.SPRICF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.VDIV           = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.VDIV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.SPRAXISET      = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.SPRAXISET);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.SPRMOD         = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.SPRMOD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.HSIZE          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.HSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.VSIZE          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.VSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.RYTA           = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.RYTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.RYDEF          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.RYDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.RCBTA          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.RCBTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.RCRTA          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.RCRTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.RCDEF          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.RCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.WYTA           = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.WYTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.WYDEF          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.WYDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.WCBTA          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.WCBTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.WCRTA          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.WCRTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.WCDEF          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.WCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_RW.TMPTA          = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_RW.TMPTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CSPREN       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CGDKEN       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CGDKEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCEN         = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCYTHH       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCYTHV       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCCTHH       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCCTHV       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCYDYM       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCYDYMDT     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCYSCL       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCYSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCYSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCYSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCCSCL       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCCSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCCSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCCSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCSSCL       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCSSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCSSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.MCSSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.MCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCEN         = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCYTHH       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCYTHV       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCCTHH       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCCTHV       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCYDYM       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCYDYMDT     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCYSCL       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCYSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCYSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCYSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCCSCL       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCCSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCCSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCCSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCSSCL       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCSSCLOF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCSSCLGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.LCSSCLBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.LCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.BLEND        = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.BLEND);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CESCLOF      = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CESCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CESCLGA      = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CESCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CESCLBD      = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CESCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CPHPT        = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CPHPT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CPHPTK       = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CPHPTK);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CDSCLOF      = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CDSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CDSCLGA      = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CDSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.CDSCLBD      = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.CDSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.WHTMD        = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.WHTMD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRS         = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRS);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRSCBOF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRSCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRSCBGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRSCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRSCBBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRSCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRSCROF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRSCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRSCRGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRSCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRSCRBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRSCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRD         = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRDCBOF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRDCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRDCBGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRDCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRDCBBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRDCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRDCROF     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRDCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRDCRGA     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRDCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_CSPR_REG.SPRDCRBD     = %lX\n", (kulong)&IO_CNR_P1.OFL_CSPR_REG.SPRDCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_YSPR.YSPREN       = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_YSPR.YSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_YSPR.YSPRMODE     = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_YSPR.YSPRMODE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_YSPR.YSPRFXEY     = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_YSPR.YSPRFXEY);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_YSPR.YSPRFXEC     = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_YSPR.YSPRFXEC);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_YSPR.YSPRALPBD    = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_YSPR.YSPRALPBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_YSPR.YSPRDYEYOF   = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_YSPR.YSPRDYEYOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_YSPR.YSPRDYEYGA   = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_YSPR.YSPRDYEYGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P1.OFL_REG_YSPR.YSPRDYEYBD   = %lX\n", (kulong)&IO_CNR_P1.OFL_REG_YSPR.YSPRDYEYBD);

    EX_CNR_TEST_RS_PRINTF(" \n");

    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.SPRSR          = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.SPRSR);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.ACESEN         = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.ACESEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.SPRTRG         = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.SPRTRG);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.SPRICE         = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.SPRICE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.SPRICF         = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.SPRICF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.HDIV           = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.HDIV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.SPRAXISET      = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.SPRAXISET);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.SPRMOD         = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.SPRMOD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.HSIZE          = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.HSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.VSIZE          = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.VSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.WCTA           = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.WCTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.WCDEF          = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.WCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_REG_RW.CNRWOFSX       = %lX\n", (kulong)&IO_CNR_P2.OTF_REG_RW.CNRWOFSX);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CSPREN       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CGDKEN       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CGDKEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCEN         = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCYTHH       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCYTHV       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCCTHH       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCCTHV       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCYDYM       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCYDYMDT     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCYSCL       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCYSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCYSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCYSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCCSCL       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCCSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCCSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCCSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCSSCL       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCSSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCSSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.MCSSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.MCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCEN         = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCYTHH       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCYTHV       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCCTHH       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCCTHV       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCYDYM       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCYDYMDT     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCYSCL       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCYSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCYSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCYSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCCSCL       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCCSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCCSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCCSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCSSCL       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCSSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCSSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.LCSSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.LCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.BLEND        = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.BLEND);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CESCLOF      = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CESCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CESCLGA      = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CESCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CESCLBD      = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CESCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CPHPT        = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CPHPT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CPHPTK       = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CPHPTK);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CDSCLOF      = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CDSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CDSCLGA      = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CDSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.CDSCLBD      = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.CDSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.WHTMD        = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.WHTMD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRS         = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRS);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRSCBOF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRSCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRSCBGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRSCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRSCBBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRSCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRSCROF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRSCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRSCRGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRSCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRSCRBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRSCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRD         = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRDCBOF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRDCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRDCBGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRDCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRDCBBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRDCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRDCROF     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRDCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRDCRGA     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRDCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OTF_CSPR_REG.SPRDCRBD     = %lX\n", (kulong)&IO_CNR_P2.OTF_CSPR_REG.SPRDCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.SPRSR          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.SPRSR);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.ACESEN         = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.ACESEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.SPRTRG         = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.SPRTRG);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.SPRICE         = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.SPRICE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.SPRICF         = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.SPRICF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.VDIV           = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.VDIV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.SPRAXISET      = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.SPRAXISET);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.SPRMOD         = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.SPRMOD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.HSIZE          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.HSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.VSIZE          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.VSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.RYTA           = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.RYTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.RYDEF          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.RYDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.RCBTA          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.RCBTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.RCRTA          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.RCRTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.RCDEF          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.RCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.WYTA           = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.WYTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.WYDEF          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.WYDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.WCBTA          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.WCBTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.WCRTA          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.WCRTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.WCDEF          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.WCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_RW.TMPTA          = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_RW.TMPTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CSPREN       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CGDKEN       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CGDKEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCEN         = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCYTHH       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCYTHV       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCCTHH       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCCTHV       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCYDYM       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCYDYMDT     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCYSCL       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCYSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCYSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCYSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCCSCL       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCCSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCCSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCCSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCSSCL       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCSSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCSSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.MCSSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.MCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCEN         = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCYTHH       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCYTHV       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCCTHH       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCCTHV       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCYDYM       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCYDYMDT     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCYSCL       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCYSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCYSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCYSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCCSCL       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCCSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCCSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCCSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCSSCL       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCSSCLOF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCSSCLGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.LCSSCLBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.LCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.BLEND        = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.BLEND);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CESCLOF      = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CESCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CESCLGA      = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CESCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CESCLBD      = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CESCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CPHPT        = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CPHPT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CPHPTK       = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CPHPTK);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CDSCLOF      = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CDSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CDSCLGA      = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CDSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.CDSCLBD      = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.CDSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.WHTMD        = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.WHTMD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRS         = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRS);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRSCBOF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRSCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRSCBGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRSCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRSCBBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRSCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRSCROF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRSCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRSCRGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRSCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRSCRBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRSCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRD         = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRDCBOF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRDCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRDCBGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRDCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRDCBBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRDCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRDCROF     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRDCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRDCRGA     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRDCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_CSPR_REG.SPRDCRBD     = %lX\n", (kulong)&IO_CNR_P2.OFL_CSPR_REG.SPRDCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_YSPR.YSPREN       = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_YSPR.YSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_YSPR.YSPRMODE     = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_YSPR.YSPRMODE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_YSPR.YSPRFXEY     = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_YSPR.YSPRFXEY);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_YSPR.YSPRFXEC     = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_YSPR.YSPRFXEC);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_YSPR.YSPRALPBD    = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_YSPR.YSPRALPBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_YSPR.YSPRDYEYOF   = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_YSPR.YSPRDYEYOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_YSPR.YSPRDYEYGA   = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_YSPR.YSPRDYEYGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P2.OFL_REG_YSPR.YSPRDYEYBD   = %lX\n", (kulong)&IO_CNR_P2.OFL_REG_YSPR.YSPRDYEYBD);

    EX_CNR_TEST_RS_PRINTF(" \n");

    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.SPRSR          = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.SPRSR);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.ACESEN         = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.ACESEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.SPRTRG         = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.SPRTRG);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.SPRICE         = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.SPRICE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.SPRICF         = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.SPRICF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.HDIV           = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.HDIV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.SPRAXISET      = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.SPRAXISET);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.SPRMOD         = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.SPRMOD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.HSIZE          = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.HSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.VSIZE          = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.VSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.WCTA           = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.WCTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.WCDEF          = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.WCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_REG_RW.CNRWOFSX       = %lX\n", (kulong)&IO_CNR_P3.OTF_REG_RW.CNRWOFSX);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CSPREN       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CGDKEN       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CGDKEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCEN         = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCYTHH       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCYTHV       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCCTHH       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCCTHV       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCYDYM       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCYDYMDT     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCYSCL       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCYSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCYSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCYSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCCSCL       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCCSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCCSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCCSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCSSCL       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCSSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCSSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.MCSSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.MCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCEN         = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCYTHH       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCYTHV       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCCTHH       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCCTHV       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCYDYM       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCYDYMDT     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCYSCL       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCYSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCYSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCYSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCCSCL       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCCSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCCSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCCSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCSSCL       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCSSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCSSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.LCSSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.LCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.BLEND        = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.BLEND);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CESCLOF      = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CESCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CESCLGA      = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CESCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CESCLBD      = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CESCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CPHPT        = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CPHPT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CPHPTK       = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CPHPTK);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CDSCLOF      = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CDSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CDSCLGA      = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CDSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.CDSCLBD      = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.CDSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.WHTMD        = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.WHTMD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRS         = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRS);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRSCBOF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRSCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRSCBGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRSCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRSCBBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRSCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRSCROF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRSCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRSCRGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRSCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRSCRBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRSCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRD         = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRDCBOF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRDCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRDCBGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRDCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRDCBBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRDCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRDCROF     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRDCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRDCRGA     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRDCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OTF_CSPR_REG.SPRDCRBD     = %lX\n", (kulong)&IO_CNR_P3.OTF_CSPR_REG.SPRDCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.SPRSR          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.SPRSR);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.ACESEN         = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.ACESEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.SPRTRG         = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.SPRTRG);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.SPRICE         = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.SPRICE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.SPRICF         = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.SPRICF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.VDIV           = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.VDIV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.SPRAXISET      = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.SPRAXISET);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.SPRMOD         = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.SPRMOD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.HSIZE          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.HSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.VSIZE          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.VSIZE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.RYTA           = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.RYTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.RYDEF          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.RYDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.RCBTA          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.RCBTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.RCRTA          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.RCRTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.RCDEF          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.RCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.WYTA           = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.WYTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.WYDEF          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.WYDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.WCBTA          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.WCBTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.WCRTA          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.WCRTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.WCDEF          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.WCDEF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_RW.TMPTA          = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_RW.TMPTA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CSPREN       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CGDKEN       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CGDKEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCEN         = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCYTHH       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCYTHV       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCCTHH       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCCTHV       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCYDYM       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCYDYMDT     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCYSCL       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCYSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCYSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCYSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCCSCL       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCCSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCCSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCCSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCSSCL       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCSSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCSSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.MCSSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.MCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCEN         = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCEN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCYTHH       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCYTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCYTHV       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCYTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCCTHH       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCCTHH);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCCTHV       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCCTHV);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCYDYM       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCYDYM);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCYDYMDT     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCYDYMDT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCYSCL       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCYSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCYSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCYSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCYSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCYSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCYSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCYSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCCSCL       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCCSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCCSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCCSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCCSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCCSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCCSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCCSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCSSCL       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCSSCL);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCSSCLOF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCSSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCSSCLGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCSSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.LCSSCLBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.LCSSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.BLEND        = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.BLEND);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CESCLOF      = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CESCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CESCLGA      = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CESCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CESCLBD      = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CESCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CPHPT        = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CPHPT);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CPHPTK       = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CPHPTK);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CDSCLOF      = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CDSCLOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CDSCLGA      = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CDSCLGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.CDSCLBD      = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.CDSCLBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.WHTMD        = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.WHTMD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRS         = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRS);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRSCBOF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRSCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRSCBGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRSCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRSCBBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRSCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRSCROF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRSCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRSCRGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRSCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRSCRBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRSCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRD         = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRDCBOF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRDCBOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRDCBGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRDCBGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRDCBBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRDCBBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRDCROF     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRDCROF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRDCRGA     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRDCRGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_CSPR_REG.SPRDCRBD     = %lX\n", (kulong)&IO_CNR_P3.OFL_CSPR_REG.SPRDCRBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_YSPR.YSPREN       = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_YSPR.YSPREN);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_YSPR.YSPRMODE     = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_YSPR.YSPRMODE);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_YSPR.YSPRFXEY     = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_YSPR.YSPRFXEY);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_YSPR.YSPRFXEC     = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_YSPR.YSPRFXEC);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_YSPR.YSPRALPBD    = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_YSPR.YSPRALPBD);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_YSPR.YSPRDYEYOF   = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_YSPR.YSPRDYEYOF);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_YSPR.YSPRDYEYGA   = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_YSPR.YSPRDYEYGA);
    EX_CNR_TEST_RS_PRINTF("IO_CNR_P3.OFL_REG_YSPR.YSPRDYEYBD   = %lX\n", (kulong)&IO_CNR_P3.OFL_REG_YSPR.YSPRDYEYBD);
#endif
    EX_CNR_TEST_RS_PRINTF(" \n");
}

ExCnrTest* ex_cnr_test_new(void)
{
    ExCnrTest* self = k_object_new_with_private(EX_TYPE_CNR_TEST, sizeof(ExCnrTestPrivate));
    return self;
}
