### Root Directory of the Project
ROOT_DIR     := ../..

### The current path from Root Directory.
DIR          := Project/Pmc

### The List of Sub-Directory which have Makefile
### note: If current directory does not have the sub-directory, Variable "SUBDIR" is empty.
SUBDIRS      :=

### List of source files
### note: If current directory does not have C/ASM source files in "src" directory, CSRC/ASRC is empty.
#CSRC := pmc.c
#CSRC := jctpmcadc.c
#CSRC := jctpmccalendar.c
#CSRC := jctpmccrg11.c
#CSRC := jctpmcexiu.c
#CSRC := jctpmcgpio.c
#CSRC := jctpmchdmac.c
#CSRC := jctpmci2c.c
#CSRC := jctpmcpmu.c
#CSRC := jctpmcsensorif.c
#CSRC := jctpmcspi.c
#CSRC := jctpmcuart.c
#CSRC := jctpmcwatchdog.c
CSRC := kpmc.c

ASRC :=




WS_DIR_NAME  ?= Project
include $(ROOT_DIR)/$(WS_DIR_NAME)/common.mk





### Special compile/assemble
